#!/bin/sh
# postinst script for deepin-desktop-schemas

set -e
data_dir=/usr/share/deepin-desktop-schemas
gschemas_dir=/usr/share/glib-2.0/schemas

case "$1" in
	configure)
        SYSTYPE=$(grep Type= /etc/deepin-version|cut -d= -f 2)
        case "$SYSTYPE" in
            Professional)
                ln -sf $data_dir/pro-override $gschemas_dir/91_deepin_product.gschema.override
            ;;

            Server)
                ln -sf $data_dir/server-override $gschemas_dir//91_deepin_product.gschema.override
            ;;
        esac
	;;
	abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
