/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./deepin-desktop-schemas/schemas/com.deepin.dde.dock.gschema.xml -a ./deepin-desktop-schemas/toolGenerate/qdbusxml2cpp/com.deepin.dde.dock.gschemaAdaptor -i ./deepin-desktop-schemas/toolGenerate/qdbusxml2cpp/com.deepin.dde.dock.gschema.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./deepin-desktop-schemas/toolGenerate/qdbusxml2cpp/com.deepin.dde.dock.gschemaAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

