/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./deepin-desktop-schemas/schemas/wrap/com.deepin.wrap.gnome.settings-daemon.plugins.orientation.gschema.xml -a ./deepin-desktop-schemas/toolGenerate/qdbusxml2cpp/com.deepin.wrap.gnome.settings-daemon.plugins.orientation.gschemaAdaptor -i ./deepin-desktop-schemas/toolGenerate/qdbusxml2cpp/com.deepin.wrap.gnome.settings-daemon.plugins.orientation.gschema.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_WRAP_GNOME_SETTINGS-DAEMON_PLUGINS_ORIENTATION_GSCHEMAADAPTOR_H
#define COM_DEEPIN_WRAP_GNOME_SETTINGS-DAEMON_PLUGINS_ORIENTATION_GSCHEMAADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./deepin-desktop-schemas/toolGenerate/qdbusxml2cpp/com.deepin.wrap.gnome.settings-daemon.plugins.orientation.gschema.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

#endif
